# ADVACCTV CONFIG FILE

[server]
    server_ip="192.168.0.20"
    server_port=2025

[properties]
    update_check_rate = 30
    update_source = "https://github.com/Advait-Nair/AdvaCCTV"

    max_log_size = 5000 # lines
    delete_top_n_lines_on_log_full = 10

    capture_clip_length = 60
    video_save_path = "./videos"
    pyv="3.12"

[flags]
    server_mode=false